export const overrideApis = () => {
  global.fetch = (api) => {
    let response = { data: {} };
    switch (api) {
      case "/api/fixtures/3":
        response.data = [
          {
            id: 2871,
            tournamentId: 3,
            category: "Ladies Junior",
            groupNumber: 2,
            pitch: "Z1",
            stage: "group",
            scheduled: "2023-11-17T07:30:00.000Z",
            scheduledTime: "08:30",
            started: null,
            startedTime: null,
            team1: "Jersey Irish",
            goals1: 0,
            points1: 2,
            team2: "Copenhagen B",
            goals2: 5,
            points2: 12,
            umpireTeam: "Hamburg",
            played: 1,
          },
          {
            id: 2873,
            tournamentId: 3,
            category: "Ladies Junior",
            groupNumber: 2,
            pitch: "Z1",
            stage: "group",
            scheduled: "2023-11-17T08:00:00.000Z",
            scheduledTime: "09:00",
            started: null,
            startedTime: null,
            team1: "Nantes/Strasbourg Gaels B",
            goals1: 1,
            points1: 2,
            team2: "Copenhagen B",
            goals2: 3,
            points2: 2,
            umpireTeam: "Leuven",
            played: 1,
          },
          {
            id: 2875,
            tournamentId: 3,
            category: "Ladies Junior",
            groupNumber: 2,
            pitch: "Z1",
            stage: "group",
            scheduled: "2023-11-17T08:30:00.000Z",
            scheduledTime: "09:30",
            started: "2023-11-17T12:18:42.000Z",
            startedTime: "13:18",
            team1: "Jersey Irish",
            goals1: 1,
            points1: 4,
            team2: "Nantes/Strasbourg Gaels B",
            goals2: 1,
            points2: 4,
            umpireTeam: "Stockholm/A Coruña",
            played: 1,
          },
          {
            id: 2879,
            tournamentId: 3,
            category: "Ladies Junior",
            groupNumber: 1,
            pitch: "Z1",
            stage: "semis",
            scheduled: "2023-11-17T11:30:00.000Z",
            scheduledTime: "12:30",
            started: "2023-11-18T21:49:16.000Z",
            startedTime: "22:49",
            team1: "Stockholm/A Coruña",
            goals1: 1,
            points1: 8,
            team2: "Nantes/Strasbourg Gaels B",
            goals2: 3,
            points2: 5,
            umpireTeam: "~group:1/p:3",
            played: 1,
          },
          {
            id: 2880,
            tournamentId: 3,
            category: "Ladies Junior",
            groupNumber: 2,
            pitch: "Z1",
            stage: "runnersup",
            scheduled: "2023-11-17T12:10:00.000Z",
            scheduledTime: "13:10",
            started: "2023-11-22T21:57:58.000Z",
            startedTime: "22:57",
            team1: "Hamburg",
            goals1: 1,
            points1: 4,
            team2: "Jersey Irish",
            goals2: 3,
            points2: 1,
            umpireTeam: "~group:1/p:3",
            played: 1,
          },
          {
            id: 2881,
            tournamentId: 3,
            category: "Ladies Junior",
            groupNumber: 2,
            pitch: "Z1",
            stage: "semis",
            scheduled: "2023-11-17T12:40:00.000Z",
            scheduledTime: "13:40",
            started: "2023-11-30T15:56:27.000Z",
            startedTime: "16:56",
            team1: "Copenhagen B",
            goals1: null,
            points1: null,
            team2: "Leuven",
            goals2: null,
            points2: null,
            umpireTeam: "~semis:2/p:2",
            played: 0,
          },
          {
            id: 2882,
            tournamentId: 3,
            category: "Ladies Junior",
            groupNumber: 1,
            pitch: "Z1",
            stage: "runnersup",
            scheduled: "2023-11-17T14:00:00.000Z",
            scheduledTime: "15:00",
            started: null,
            startedTime: null,
            team1: "~semis:1/p:2",
            goals1: null,
            points1: null,
            team2: "~semis:2/p:2",
            goals2: null,
            points2: null,
            umpireTeam: "~group:1/p:1",
            played: 0,
          },
          {
            id: 2883,
            tournamentId: 3,
            category: "Ladies Junior",
            groupNumber: 1,
            pitch: "Z1",
            stage: "finals",
            scheduled: "2023-11-17T14:30:00.000Z",
            scheduledTime: "15:30",
            started: null,
            startedTime: null,
            team1: "Stockholm/A Coruña",
            goals1: null,
            points1: null,
            team2: "~semis:2/p:1",
            goals2: null,
            points2: null,
            umpireTeam: "~group:1/p:2",
            played: 0,
          },
        ];
        break;
      case "/api/whatever":
        response.data = [
          { Id: "1", Title: "Big Tournament" },
          { Id: "2", Title: "Little Tournament" },
          { Id: "3", Title: "Another Tournament" },
        ];
        break;
      default:
        response = { error: "No data for api " + api };
    }

    return Promise.resolve({
      ok: true,
      json: () => Promise.resolve(response)
    });
  };
};
